### ISSUE TITLE
Follow up - Update all component tables with filtering

### ISSUE THREAD

**Issue by cpholguera** [OWASP/mastg#3300]
We're currently using datatables but it doesn't support filters.

See mkdocs.yml:

```yml
extra_css:
  - stylesheets/extra.css
  - https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css
extra_javascript:
  - javascripts/external_links.js
  - https://code.jquery.com/jquery-3.5.1.js
  - https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js
  - javascripts/datatables.js
```

We'd like the tables in tests, tools, etc. to be like:

<img width="1892" alt="Image" src="https://github.com/user-attachments/assets/463e9dce-8614-455f-b02c-0d1a8f22c917" />

See https://www.ag-grid.com/javascript-data-grid/themes/
